name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: Prepare deploy folder
        run: rm -rf _gh-pages && mkdir _gh-pages

      - name: Build all slides
        run: |
          BASE_PATH=$(node slide-decks/scripts/getBase.ts)

          for slide in slides/*; do
            slide_name=$(basename "$slide")
            pnpm --filter "./slides/$slide_name" run build --base $BASE_PATH/$slide_name/

            if [ -d "$slide/dist" ]; then
              mkdir -p "_gh-pages/$slide_name"
              cp -r "$slide/dist/." "_gh-pages/$slide_name/"
            fi
          done

      - name: Build slide decks app as index
        run: |
          pnpm --filter ./slide-decks run build
          mkdir -p "_gh-pages"
          cp -r slide-decks/dist/. "_gh-pages/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
